### PR TITLE
chore(*): upgrade for support w/ socket.io v2

### PR DESCRIPTION
**Pull request by amcdnl**
Upgrades the adapters for socket v2.0 support

### CODE REVIEW

**Comment by lklepner** [comment]
Tests are failing - 

$ mocha


  socket.io-mongo
    1) "before each" hook


  0 passing (34ms)
  1 failing

  1) socket.io-mongo "before each" hook:
     Uncaught MongoError: Authentication failed.
      at Function.MongoError.create (node_modules/mongodb-core/lib/error.js:31:11)
      at node_modules/mongodb-core/lib/connection/pool.js:497:72
      at authenticateStragglers (node_modules/mongodb-core/lib/connection/pool.js:443:16)
      at Connection.messageHandler (node_modules/mongodb-core/lib/connection/pool.js:477:5)
      at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:331:22)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:547:20)

**Comment by amcdnl** [comment]
Tests ran for me fine locally, I had to change the connection info to my real mongo instance though.

**Comment by lklepner** [comment]
Here is the failed test -
https://travis-ci.org/lklepner/socket.io-adapter-mongo/jobs/267702843

The Travis config was only set to test node 0.10 and 0.11. 

I just updated master to test 4.x - 7.x. 

Would you mind opening a new PR pointing towards the v2.0.0 branch I just created? I think this would be the easiest/safest way for us to work through the failing tests and prepare a clean release.

**Comment by amcdnl** [comment]
done.

**Pull request closed without merging**
